// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto
#ifndef GRPC_hello_2eproto__INCLUDED
#define GRPC_hello_2eproto__INCLUDED

#include "hello.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc_impl {
class CompletionQueue;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc_impl

namespace grpc {
namespace experimental {
template <typename RequestT, typename ResponseT>
class MessageAllocator;
}  // namespace experimental
}  // namespace grpc

namespace helloworld {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "helloworld.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::helloworld::HellResp* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HellResp>> AsyncSayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HellResp>>(AsyncSayHiRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HellResp>> PrepareAsyncSayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HellResp>>(PrepareAsyncSayHiRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHi(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helloworld::HellResp* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      virtual void SayHi(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helloworld::HellResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HellResp>* AsyncSayHiRaw(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::helloworld::HellResp>* PrepareAsyncSayHiRaw(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::helloworld::HellResp* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>> AsyncSayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>>(AsyncSayHiRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>> PrepareAsyncSayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>>(PrepareAsyncSayHiRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response, std::function<void(::grpc::Status)>) override;
      void SayHi(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helloworld::HellResp* response, std::function<void(::grpc::Status)>) override;
      void SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      void SayHi(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helloworld::HellResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>* AsyncSayHiRaw(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>* PrepareAsyncSayHiRaw(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SayHi_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SayHi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_SayHi() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SayHi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHi(::grpc::ServerContext* context, ::helloworld::HelloReq* request, ::grpc::ServerAsyncResponseWriter< ::helloworld::HellResp>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SayHi<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SayHi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_SayHi() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::helloworld::HelloReq, ::helloworld::HellResp>(
          [this](::grpc::ServerContext* context,
                 const ::helloworld::HelloReq* request,
                 ::helloworld::HellResp* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->SayHi(context, request, response, controller);
                 }));
    }
    void SetMessageAllocatorFor_SayHi(
        ::grpc::experimental::MessageAllocator< ::helloworld::HelloReq, ::helloworld::HellResp>* allocator) {
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::helloworld::HelloReq, ::helloworld::HellResp>*>(
          ::grpc::Service::experimental().GetHandler(0))
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SayHi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_SayHi<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SayHi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_SayHi() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SayHi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SayHi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_SayHi() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SayHi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSayHi(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SayHi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_SayHi() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->SayHi(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_SayHi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void SayHi(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SayHi : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_SayHi() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::helloworld::HelloReq, ::helloworld::HellResp>(std::bind(&WithStreamedUnaryMethod_SayHi<BaseClass>::StreamedSayHi, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_SayHi() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSayHi(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::helloworld::HelloReq,::helloworld::HellResp>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SayHi<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SayHi<Service > StreamedService;
};

}  // namespace helloworld


#endif  // GRPC_hello_2eproto__INCLUDED
