// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hello.proto

#include "hello.pb.h"
#include "hello.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace helloworld {

static const char* Greeter_method_names[] = {
  "/helloworld.Greeter/SayHi",
};

std::unique_ptr< Greeter::Stub> Greeter::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Greeter::Stub> stub(new Greeter::Stub(channel));
  return stub;
}

Greeter::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_SayHi_(Greeter_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Greeter::Stub::SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::helloworld::HellResp* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_SayHi_, context, request, response);
}

void Greeter::Stub::experimental_async::SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHi_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::SayHi(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helloworld::HellResp* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_SayHi_, context, request, response, std::move(f));
}

void Greeter::Stub::experimental_async::SayHi(::grpc::ClientContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayHi_, context, request, response, reactor);
}

void Greeter::Stub::experimental_async::SayHi(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::helloworld::HellResp* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_SayHi_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>* Greeter::Stub::AsyncSayHiRaw(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helloworld::HellResp>::Create(channel_.get(), cq, rpcmethod_SayHi_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::helloworld::HellResp>* Greeter::Stub::PrepareAsyncSayHiRaw(::grpc::ClientContext* context, const ::helloworld::HelloReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::helloworld::HellResp>::Create(channel_.get(), cq, rpcmethod_SayHi_, context, request, false);
}

Greeter::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Greeter_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Greeter::Service, ::helloworld::HelloReq, ::helloworld::HellResp>(
          std::mem_fn(&Greeter::Service::SayHi), this)));
}

Greeter::Service::~Service() {
}

::grpc::Status Greeter::Service::SayHi(::grpc::ServerContext* context, const ::helloworld::HelloReq* request, ::helloworld::HellResp* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace helloworld

